ubuntu-wsl: bring some stuff over from osx

diff --git a/install.conf.yaml b/install.conf.yaml
--- a/install.conf.yaml
+++ b/install.conf.yaml
@@ -2,12 +2,15 @@
     link:
       create: true
       relink: true
+    shell:
+      stdout: true
+      stderr: true
+      quiet: true
 
 - clean: ['~']
 
 - link:
-    # in wsl, file needs to exist in %AppData%/alacritty/alacritty.toml and be linked to wsl for editing
-    # ~/.config/alacritty/alacritty.toml: alacritty/alacritty.toml
+    ~/.config/alacritty/alacritty.toml: alacritty/alacritty.toml
     ~/.config/coc/extensions/package.json: coc/package.json
     ~/.config/coc/ultisnips: coc/ultisnips
     ~/.config/nvim/coc-settings.json: nvim/coc-settings.json
@@ -23,11 +26,63 @@
     ~/.tmux.conf: tmux/.tmux.conf
     ~/.urlview: urlview/.urlview
     ~/.zprofile: zsh/.zprofile
-    ~/.zsh_plugins.sh: zsh/.zsh_plugins.sh
-    ~/.zshrc: zsh/.zshrc
+    ~/.zsh_plugins.txt: zsh/.zsh_plugins.txt
+    ~/.zshrc:
+      path: zsh/.zshrc
+      force: true
+
+- create:
+    - ~/bin
+    - ~/opt
+    - ~/.ssh
 
 - shell:
-    # Add special terminfos so we can use italics
-    - [tic terminfo/xterm-256color.terminfo]
-    - [tic terminfo/tmux.terminfo]
-    - [tic terminfo/tmux-256color.terminfo]
+    -
+      description: Installing submodules
+      command: git submodule update --init --recursive
+    -
+      description: Add special terminfos so we can use italics
+      command: |
+        tic terminfo/xterm-256color.terminfo
+        tic terminfo/tmux.terminfo
+        tic terminfo/xterm-256color.terminfo
+    -
+      description: Install brew packages (osx only)
+      command: |
+        if ! command -v brew &> /dev/null
+        then
+          echo "brew not found"
+          echo "see: https://brew.sh/"
+          exit 1
+        else
+          brew bundle
+        fi
+    - description: Install rust packages
+      command: |
+        if ! command -v cargo &> /dev/null
+        then
+          echo "cargo not found"
+          echo "see: https://www.rust-lang.org/learn/get-started"
+          exit 1
+        else
+          cargo install cargo-update
+          cargo install ripgrep
+          cargo install bat
+          cargo install exa
+          cargo install fd-find
+        fi
+    - description: Install Tmux Plugin Manager
+      command: |
+        if ! test -d ~/.tmux/plugins/tpm; then
+          git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
+        else
+          echo "TPM already installed"
+        fi
+    - description: Check for existence of desired commands
+      command: |
+        /bin/bash check_cmd.sh fnm "https://github.com/Schniz/fnm"
+        /bin/bash check_cmd.sh starship "https://starship.rs/"
+        /bin/bash check_cmd.sh fzf "https://github.com/junegunn/fzf"
+        /bin/bash check_cmd.sh pyenv "https://github.com/pyenv/pyenv"
+        /bin/bash check_cmd.sh pdm "https://pdm-project.org/en/latest/"
+        /bin/bash check_cmd.sh nnn "https://github.com/jarun/nnn"
