osx: fix brew stuff

diff --git a/install.conf.yaml b/install.conf.yaml
--- a/install.conf.yaml
+++ b/install.conf.yaml
@@ -49,10 +49,10 @@
     -
       description: Install brew packages (osx only)
       command: |
-        if ! command -v cargo &> /dev/null
+        if ! command -v brew &> /dev/null
         then
-          echo "cargo not found"
-          echo "see: https://www.rust-lang.org/learn/get-started"
+          echo "brew not found"
+          echo "see: https://brew.sh/"
           exit 1
         else
           brew bundle
